# tests/test_archive_commons.py
import pytest

import footage.archive_types as types_mod
from footage.archive_commons import AI_MARKERS, looks_ai_generated, parse_commons_response, search_commons_photos
from footage.archive_types import (
    ArchiveCandidate, ArchiveError, USER_AGENT, fetch_to_file, get_json, strip_html, year_from,
)


def _page(index, *, width=3000, height=2000, mime="image/jpeg", license_="pd", short="Public domain",
          copyrighted="False", original="1864-09-27", with_thumb=True, extra_meta=None):
    info = {
        "width": width, "height": height, "mime": mime,
        "url": f"https://upload.wikimedia.org/original/{index}.jpg",
        "descriptionurl": f"https://commons.wikimedia.org/wiki/File:{index}.jpg",
        "extmetadata": {
            "ObjectName": {"value": f"Photo <i>{index}</i>"},
            "Artist": {"value": "<a href='x'>Matthew Brady</a>"},
            "DateTimeOriginal": {"value": original},
            "License": {"value": license_}, "LicenseShortName": {"value": short},
            "Copyrighted": {"value": copyrighted},
        },
    }
    for key, value in (extra_meta or {}).items():
        info["extmetadata"][key] = {"value": value}
    if copyrighted is None:
        del info["extmetadata"]["Copyrighted"]
    if with_thumb:
        info.update({"thumburl": f"https://upload.wikimedia.org/thumb/{index}.jpg", "thumbwidth": 1920,
                     "thumbheight": 1280})
    return {"pageid": index, "index": index, "title": f"File:{index}.jpg", "imageinfo": [info]}


def _payload(*pages):
    return {"query": {"pages": {str(p["pageid"]): p for p in pages}}}


def test_a_public_domain_photo_becomes_a_candidate_with_its_source_and_rights():
    [c] = parse_commons_response(_payload(_page(1)))

    assert c == ArchiveCandidate(
        source="commons", item_id="1", kind="photo", title="Photo 1", year=1864, creator="Matthew Brady",
        rights="Public domain", page_url="https://commons.wikimedia.org/wiki/File:1.jpg",
        media_url="https://upload.wikimedia.org/thumb/1.jpg", thumbnail_url="https://upload.wikimedia.org/thumb/1.jpg",
        width=1920, height=1280)
    assert c.display_id == "commons:1"


def test_results_keep_the_search_order_from_the_index_field():
    candidates = parse_commons_response(_payload(_page(3), _page(1), _page(2)))

    assert [c.item_id for c in candidates] == ["1", "2", "3"]


def test_a_photo_smaller_than_the_1920_thumbnail_is_used_at_its_original_url():
    [c] = parse_commons_response(_payload(_page(1, width=1500, height=1000)))

    assert c.media_url == "https://upload.wikimedia.org/original/1.jpg"
    assert (c.width, c.height) == (1500, 1000)


@pytest.mark.parametrize("kwargs", [
    {"license_": "cc-by-sa-4.0", "short": "CC BY-SA 4.0"},     # attribution licenses are not public domain
    {"license_": "cc-by-4.0", "short": "CC BY 4.0"},
    {"license_": "", "short": ""},                              # unclear rights are dropped
    {"copyrighted": "True"},                                    # explicitly copyrighted
    {"mime": "image/svg+xml"}, {"mime": "image/tiff"},          # not a photo the renderer takes
    {"width": 800, "height": 600},                              # too small for a full-frame photo
])
def test_unclear_restricted_or_unusable_photos_never_become_candidates(kwargs):
    assert parse_commons_response(_payload(_page(1, **kwargs))) == []


def test_a_public_domain_file_with_no_copyrighted_field_is_accepted():
    assert len(parse_commons_response(_payload(_page(1, copyrighted=None)))) == 1


def test_a_wide_photo_without_a_thumbnail_falls_back_to_the_original():
    [c] = parse_commons_response(_payload(_page(1, width=3000, height=2000, with_thumb=False)))

    assert c.media_url == "https://upload.wikimedia.org/original/1.jpg"
    assert (c.width, c.height) == (3000, 2000)


def test_cc0_counts_as_open():
    assert len(parse_commons_response(_payload(_page(1, license_="cc0", short="CC0")))) == 1


def test_a_page_without_imageinfo_is_skipped():
    assert parse_commons_response(_payload({"pageid": 9, "index": 1, "title": "File:x.jpg"})) == []


def test_a_known_year_outside_the_range_is_dropped_and_an_unknown_year_is_dropped_too():
    pages = _payload(_page(1, original="1864"), _page(2, original="1990"), _page(3, original=""))

    kept = parse_commons_response(pages, year_range=(1850, 1880))

    assert [c.item_id for c in kept] == ["1"]


@pytest.mark.parametrize("extra", [
    {"Categories": "AI-generated images|Paintings"},
    {"ImageDescription": "Created with Midjourney"},
    {"Credit": "Generated by Stable Diffusion"},
    {"UsageTerms": "CC0 (AI generated, no copyright)"},
    {"Software": "DALL-E 3"},
    {"Artist": "MIDJOURNEY user"},
    {"ObjectName": "A Dall\u00b7E picture"},
])
def test_a_candidate_with_an_ai_marker_in_its_metadata_is_dropped(extra):
    assert parse_commons_response(_payload(_page(1, extra_meta=extra))) == []


@pytest.mark.parametrize("extra", [
    {"ImageDescription": "Imagen de la batalla"},
    {"ObjectName": "Steamer Firefly, 1862"},
    {"Credit": "Photo generated by the Works Progress Administration"},
    {"Artist": "Dalle Molle family"},
    {"ImageDescription": "Image generated by camera"},
])
def test_legitimate_history_that_shares_a_word_with_an_ai_tool_is_not_flagged_and_is_kept(extra):
    assert not looks_ai_generated({k: {"value": v} for k, v in extra.items()})
    assert len(parse_commons_response(_payload(_page(1, extra_meta=extra)))) == 1


@pytest.mark.parametrize("text", [
    "Thai art", "Thai image of a temple", "Shanghai art collection", "Shanghai image 1900", "Bonsai art",
    "Kauai image", "Mai image", "Taipei art", "Chair image", "The Night Cafe",
])
def test_ai_markers_never_match_inside_ordinary_words(text):
    assert not looks_ai_generated({"ImageDescription": {"value": text}})
    assert len(parse_commons_response(_payload(_page(1, extra_meta={"ImageDescription": text})))) == 1


@pytest.mark.parametrize("text", [
    "AI art", "an AI image of a battle", "(AI image)", "Image: AI art.", "ai-generated", "Created with Midjourney",
    "Adobe Firefly", "OpenAI DALL-E 3", "Category: AI-generated images", "Upscaled by AI", "Stability AI SDXL",
    "Nightcafe, Arles", "DALL\u00b7E", "leonardo.ai", "AI-assisted", "ai-upscaled",
])
def test_ai_markers_match_on_word_boundaries(text):
    assert looks_ai_generated({"ImageDescription": {"value": text}})
    assert parse_commons_response(_payload(_page(1, extra_meta={"ImageDescription": text}))) == []


def test_a_marker_cannot_span_two_fields():
    assert not looks_ai_generated({"Credit": {"value": "made with"}, "Artist": {"value": "ai"}})


@pytest.mark.parametrize("extra", [
    {"ImageDescription": "Created with Midjourney"},
    {"Credit": "Generated by AI"},
    {"Software": "Adobe Firefly"},
    {"Credit": "Stable Diffusion v1.5"},
    {"Software": "DALL-E 3"},
    {"Categories": "Category: AI-generated images"},
    {"ImageDescription": "made with AI, Google Imagen 3"},
    {"Credit": "OpenAI"},
])
def test_ai_specific_phrases_are_flagged_and_dropped(extra):
    assert looks_ai_generated({k: {"value": v} for k, v in extra.items()})
    assert parse_commons_response(_payload(_page(1, extra_meta=extra))) == []


@pytest.mark.parametrize("original,kept", [
    ("1860", True), ("1860s reprint 1995", False), ("1990 (scan of 1860 photo)", False),
    ("between 1860 and 1865", True), ("", False), ("1961", False), ("1960", True),
])
def test_every_year_in_the_date_field_must_be_1960_or_earlier(original, kept):
    assert (len(parse_commons_response(_payload(_page(1, original=original)))) == 1) is kept


def test_all_years_finds_every_four_digit_year():
    from footage.archive_types import all_years
    assert all_years("1860s reprint 1995") == [1860, 1995] and all_years("c1888.") == [1888] and all_years("") == []


def test_looks_ai_generated_is_case_insensitive_and_strips_html():
    assert looks_ai_generated({"Categories": {"value": "<a>AI-GENERATED images</a>"}})
    assert not looks_ai_generated({"Categories": {"value": "Photographs by Matthew Brady"}})
    assert not looks_ai_generated({})
    assert "stable diffusion" in AI_MARKERS and "ai-generated" in AI_MARKERS


def test_a_clean_public_domain_photo_dated_1864_is_kept():
    assert len(parse_commons_response(_payload(_page(1, original="1864", extra_meta={
        "Categories": "American Civil War|Photographs", "Credit": "Library of Congress"})))) == 1


def test_a_candidate_with_no_known_creation_year_is_dropped():
    assert parse_commons_response(_payload(_page(1, original=""))) == []


def test_the_creation_year_must_be_1960_or_earlier():
    kept = parse_commons_response(_payload(_page(1, original="1960"), _page(2, original="1961"),
                                           _page(3, original="1999")))

    assert [c.item_id for c in kept] == ["1"]


def test_no_results_is_an_empty_list_not_an_error():
    assert parse_commons_response({"batchcomplete": ""}) == []


def test_search_sends_a_bitmap_search_with_the_project_user_agent(monkeypatch):
    seen = {}

    class Resp:
        status_code = 200
        def json(self): return _payload(_page(1))

    def fake_get(url, params=None, headers=None, timeout=None, **kw):
        seen.update(url=url, params=params, headers=headers)
        return Resp()

    monkeypatch.setattr(types_mod.requests, "get", fake_get)

    result = search_commons_photos("atlanta railroad 1860s", limit=7)

    assert len(result) == 1
    assert seen["url"] == "https://commons.wikimedia.org/w/api.php"
    assert seen["params"]["gsrsearch"] == "atlanta railroad 1860s filetype:bitmap"
    assert seen["params"]["gsrlimit"] == 7 and seen["params"]["gsrnamespace"] == 6
    assert seen["headers"]["User-Agent"] == USER_AGENT == "VersedVideoGenerator/0.1"


def test_get_json_raises_archive_error_on_a_bad_status(monkeypatch):
    class Resp:
        status_code = 429
        text = "slow down"

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Resp())

    with pytest.raises(ArchiveError, match="429"):
        get_json("https://example.org/api", {})


def test_get_json_raises_archive_error_on_non_json(monkeypatch):
    class Resp:
        status_code = 200
        text = "<html>"
        def json(self): raise ValueError("no json")

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Resp())

    with pytest.raises(ArchiveError, match="not JSON"):
        get_json("https://example.org/api", {})


def test_get_json_raises_archive_error_on_a_200_api_error_body(monkeypatch):
    class Resp:
        status_code = 200
        def json(self): return {"error": {"code": "maxlag", "info": "Waiting for a database server"}}

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Resp())

    with pytest.raises(ArchiveError, match="Waiting for a database server"):
        get_json("https://example.org/api", {})


def test_get_json_raises_archive_error_on_a_json_list(monkeypatch):
    class Resp:
        status_code = 200
        def json(self): return [1, 2]

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Resp())

    with pytest.raises(ArchiveError, match="unexpected JSON"):
        get_json("https://example.org/api", {})


def test_network_failures_become_archive_errors_for_both_helpers(monkeypatch, tmp_path):
    def boom(*a, **k): raise types_mod.requests.Timeout("timed out")

    monkeypatch.setattr(types_mod.requests, "get", boom)

    with pytest.raises(ArchiveError, match="timed out"):
        get_json("https://example.org/api", {})
    with pytest.raises(ArchiveError, match="timed out"):
        fetch_to_file("https://example.org/x.jpg", str(tmp_path / "x.jpg"))


def test_fetch_to_file_closes_the_response(monkeypatch, tmp_path):
    closed = []

    class Good:
        status_code = 200
        def iter_content(self, chunk_size): return iter([b"a"])
        def close(self): closed.append(True)

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Good())
    fetch_to_file("https://example.org/x.jpg", str(tmp_path / "x.jpg"))
    assert closed == [True]


def test_fetch_to_file_writes_the_bytes_and_removes_a_partial_file_on_failure(monkeypatch, tmp_path):
    class Good:
        status_code = 200
        def iter_content(self, chunk_size): return iter([b"ab", b"cd"])
        def close(self): pass

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Good())
    dest = tmp_path / "sub" / "x.jpg"
    assert fetch_to_file("https://example.org/x.jpg", str(dest)) == str(dest)
    assert dest.read_bytes() == b"abcd"

    class Bad:
        status_code = 404
        def iter_content(self, chunk_size): return iter([])
        def close(self): pass

    monkeypatch.setattr(types_mod.requests, "get", lambda *a, **k: Bad())
    with pytest.raises(ArchiveError, match="404"):
        fetch_to_file("https://example.org/missing.jpg", str(tmp_path / "y.jpg"))
    assert not (tmp_path / "y.jpg").exists()


def test_helpers():
    assert strip_html("A <b>bold</b> &amp; plain") == "A bold & plain"
    assert year_from("c1888.") == 1888 and year_from("1864-09-27") == 1864 and year_from("no year") is None
    assert year_from("ca. 1850s") == 1850
    c = ArchiveCandidate("loc", "2018/66 985", "photo", "t", None, "", "", "", "", "")
    assert c.safe_id == "loc_2018_66_985"


# --- get_json: one retry on a transient network error -------------------------------------------
import requests as _requests
import footage.archive_types as _types


class _JsonResp:
    def __init__(self, status=200): self.status_code = status; self.text = ""
    def json(self): return {"ok": 1}


def _script(monkeypatch, outcomes):
    calls, sleeps = [], []
    def fake_get(*a, **k):
        calls.append(1)
        o = outcomes[len(calls) - 1]
        if isinstance(o, Exception):
            raise o
        return o
    monkeypatch.setattr(_types.requests, "get", fake_get)
    monkeypatch.setattr(_types.time, "sleep", sleeps.append)
    return calls, sleeps


def test_get_json_retries_once_after_a_timeout(monkeypatch):
    calls, sleeps = _script(monkeypatch, [_requests.Timeout("slow"), _JsonResp()])
    assert _types.get_json("http://x", {}) == {"ok": 1}
    assert len(calls) == 2 and sleeps == [1.0]


def test_get_json_retries_once_after_a_connection_error(monkeypatch):
    calls, _ = _script(monkeypatch, [_requests.ConnectionError("reset"), _JsonResp()])
    assert _types.get_json("http://x", {}) == {"ok": 1}


def test_get_json_gives_up_after_two_timeouts(monkeypatch):
    calls, _ = _script(monkeypatch, [_requests.Timeout("a"), _requests.Timeout("b")])
    with pytest.raises(_types.ArchiveError):
        _types.get_json("http://x", {})
    assert len(calls) == 2


def test_get_json_does_not_retry_an_http_error(monkeypatch):
    calls, sleeps = _script(monkeypatch, [_JsonResp(429), _JsonResp()])
    with pytest.raises(_types.ArchiveError):
        _types.get_json("http://x", {})
    assert len(calls) == 1 and sleeps == []
