# footage/archive_commons.py
"""Wikimedia Commons photo search. Only public-domain / CC0 files with a usable size are kept."""
import re
from typing import Optional

from footage.archive_types import (
    MIN_PHOTO_LONG_SIDE, ArchiveCandidate, get_json, all_years, strip_html, year_from,
)

from shot_list.models import ARCHIVAL_CUTOFF_YEAR

COMMONS_API = "https://commons.wikimedia.org/w/api.php"
_PHOTO_MIMES = ("image/jpeg", "image/png")
_MAX_WIDTH = 1920  # the rendered picture
_THUMB_WIDTH = 960  # what the judge looks at (a standard Wikimedia thumbnail step, served from cache)
_THUMB_WIDTH_RE = re.compile(rf"/{_THUMB_WIDTH}px-")


def _meta(extmetadata: dict, key: str) -> str:
    return str((extmetadata.get(key) or {}).get("value", ""))


def _is_open(extmetadata: dict) -> bool:
    if _meta(extmetadata, "Copyrighted").lower() == "true":
        return False
    license_ = _meta(extmetadata, "License").lower()
    short = _meta(extmetadata, "LicenseShortName").lower()
    return license_.startswith("pd") or license_ == "cc0" or short.startswith("public domain") or short == "cc0"


# Lower-case substrings that mark a Commons file as AI-made.
AI_MARKERS = (
    "ai-generated", "ai generated", "ai-created", "ai created", "artificial intelligence", "stable diffusion",
    "midjourney", "dall-e", "dall\u00b7e", "text-to-image", "machine-generated", "neural network", "gan-generated",
    "generated by ai", "generated with ai", "generated using ai", "generated by midjourney",
    "generated by stable diffusion", "created with ai", "created by ai", "made with ai", "made by ai",
    "generative ai", "generative fill", "ai art", "ai image", "ai-assisted", "adobe firefly", "google imagen",
    "imagen 2", "imagen 3", "dall-e 2", "dall-e 3", "openai", "leonardo.ai", "playground ai", "nightcafe",
    "ai-upscaled", "upscaled by ai", "ai upscaled", "stability ai", "sdxl",
)
_AI_FIELDS = ("Categories", "ImageDescription", "Artist", "Credit", "ObjectName", "UsageTerms", "Software")


# A marker matches only as whole words ("Thai art", "Shanghai image" must not match "ai art", "ai image").
_AI_RE = re.compile(r"(?<![a-z0-9])(?:" + "|".join(re.escape(m) for m in AI_MARKERS) + r")(?![a-z0-9])")


def looks_ai_generated(extmetadata: dict) -> bool:
    return any(_AI_RE.search(strip_html(_meta(extmetadata, key)).lower()) for key in _AI_FIELDS)


def parse_commons_response(payload: dict, year_range: Optional[tuple] = None) -> list[ArchiveCandidate]:
    pages = (payload.get("query") or {}).get("pages") or {}
    candidates = []
    for page in sorted(pages.values(), key=lambda p: p.get("index", 0)):
        infos = page.get("imageinfo") or []
        if not infos:
            continue
        info = infos[0]
        if info.get("mime") not in _PHOTO_MIMES:
            continue
        width, height = int(info.get("width", 0)), int(info.get("height", 0))
        if max(width, height) < MIN_PHOTO_LONG_SIDE:
            continue
        meta = info.get("extmetadata") or {}
        if not _is_open(meta):
            continue
        # AI images are routinely tagged CC0/public domain on Commons, so the rights filter cannot catch them:
        # drop anything with an AI marker, and anything without a known creation year of 1960 or earlier.
        if looks_ai_generated(meta):
            continue
        date_text = _meta(meta, "DateTimeOriginal")
        year = year_from(date_text)
        years = all_years(date_text)
        # Every year named in the date must be 1960 or earlier ("1860s reprint 1995" is a modern file).
        if not years or max(years) > ARCHIVAL_CUTOFF_YEAR:
            continue
        if year_range and not (year_range[0] <= year <= year_range[1]):
            continue
        # The judge looks at the API's small thumburl (iiurlwidth=_THUMB_WIDTH), never the full-size original:
        # originals fetched as thumbnails drew 27 HTTP 429s in one live run (2026-10-07/08). The picture that is
        # rendered is the same thumbnail at _MAX_WIDTH when the original is wider than that, else the original.
        thumb_url = info.get("thumburl") or ""
        media_url, media_w, media_h = info["url"], width, height
        if width > _MAX_WIDTH and _THUMB_WIDTH_RE.search(thumb_url):
            media_url = _THUMB_WIDTH_RE.sub(f"/{_MAX_WIDTH}px-", thumb_url, count=1)
            media_w, media_h = _MAX_WIDTH, round(height * _MAX_WIDTH / width)
        candidates.append(ArchiveCandidate(
            source="commons", item_id=str(page["pageid"]), kind="photo",
            title=strip_html(_meta(meta, "ObjectName")) or page.get("title", ""), year=year,
            creator=strip_html(_meta(meta, "Artist")), rights=_meta(meta, "LicenseShortName") or "Public domain",
            page_url=info.get("descriptionurl", ""), media_url=media_url, thumbnail_url=thumb_url or media_url,
            width=media_w, height=media_h,
        ))
    return candidates


def search_commons_photos(query: str, year_range: Optional[tuple] = None, limit: int = 15) -> list[ArchiveCandidate]:
    payload = get_json(COMMONS_API, {
        "action": "query", "generator": "search", "gsrnamespace": 6,
        "gsrsearch": f"{query} filetype:bitmap", "gsrlimit": limit,
        "prop": "imageinfo", "iiprop": "url|size|mime|extmetadata", "iiurlwidth": _THUMB_WIDTH, "format": "json",
    })
    return parse_commons_response(payload, year_range)
